#!/usr/bin/env bash
set -e

help() {
  cat <<EOF
Usage: gh stashes
Displays an interactive stash selector that lists your stashes with preview that display 'git show -p -G<QUERY> <SELECTED_STASH>'
The selected stash is applied.
Dependencies: fzf
EOF
}

case "$1"
in -h | --help)
  help
  exit 0
esac

if ! type -p fzf >/dev/null; then
  echo "error: install \`fzf\` to use this command" >&2
  exit 1
fi

choose_stash() {
  local git_stash_list='git stash list'
  local extract_stash_name="grep  -o '^\(.*\)}'"
  local check_empty_string="grep '.'"
  local preview_command=$(cat <<- EOD
    git stash show --color -G{q} -p (echo {} | $extract_stash_name) | $check_empty_string ||
    git stash show --color -p  (echo {} | $extract_stash_name | $check_empty_string || echo 'unmatched. raise error' ) 2>/dev/null
EOD
)

  FZF_DEFAULT_COMMAND="$git_stash_list --color" \
  fzf --bind "change:reload:echo 'if [ -z {q} ]; then $git_stash_list; else $git_stash_list -G{q}; fi' | bash || true" \
        --ansi --disabled \
        --preview "$preview_command" \
        --preview-window '60%' \
  | eval "$extract_stash_name"
}

selected_stash="$(choose_stash)"
[ -n "$selected_stash" ] || exit 1
git stash apply "$selected_stash"